services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/NovaPlan
      - SPAWN_PYTHON=false
    depends_on:
      - database

  roadmap_ai:
    build: ./Roadmap_RC_v0.1
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_PYTHON_API_URL=http://python-ai:8000
    depends_on:
      - roadmap_ai
      - backend

volumes:
  mongo_data: